// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "GET Request Copy",
    id: "5179da10-669c-4e69-9f34-777cf8dd672f",
    method: "GET",
    address: "https://reqres.in/api/users",
    post(response) {
      pm.test("Response status code is 200", function() {
        pm.response.to.have.status(200);
      });

      pm.test("Response time is less than 1s", function() {
        pm.expect(pm.response.responseTime).to.be.below(1000);
      });

      pm.test("First name is correct", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData.data[0].first_name).to.equal("George");
      });

      pm.test("Last name is correct", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData.data[0].last_name).to.equal("Bluth");
      });

      pm.test("Email is correct", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData.data[0].email).to.equal("george.bluth@reqres.in");
      });

      pm.test("Content type is JSON", function() {
        pm.response.to.be.json;
      });
    }
  });

  postman[Request]({
    name: "POST Request Copy",
    id: "c2627997-fc30-4f5c-b193-f019ce85baba",
    method: "POST",
    address: "https://reqres.in/api/users/1",
    data:
      '{\n    "id": 1,\n    "firstName": "Akash",\n    "lastName": "Singh",\n    "age": 23,\n    "gender": "male",\n    "email": "akash.singh@knoldus.com",\n    "phone": "+91 9667305597",\n    "username": "akash1874",\n    "password": "testDummy",\n    "DateOfBirth": "1999-07-15",\n    "bloodGroup": "AB +",\n    "height": 165,\n    "weight": 71.1,\n    "eyeColor": "black",\n    "hair": {\n        "color": "Black"\n    }\n}',
    post(response) {
      pm.test("Status code is 201", function() {
        pm.response.to.have.status(201);
      });

      pm.test("Content type is JSON", function() {
        pm.response.to.be.json;
      });

      pm.test("User data is correct", function() {
        pm.expect(pm.response.json().firstName).to.eql("Akash");
        pm.expect(pm.response.json().lastName).to.eql("Singh");
        pm.expect(pm.response.json().age).to.eql(23);
        pm.expect(pm.response.json().gender).to.eql("male");
        pm.expect(pm.response.json().email).to.eql("akash.singh@knoldus.com");
        pm.expect(pm.response.json().phone).to.eql("+91 9667305597");
        pm.expect(pm.response.json().username).to.eql("akash1874");
        pm.expect(pm.response.json().password).to.eql("testDummy");
        pm.expect(pm.response.json().DateOfBirth).to.eql("1999-07-15");
        pm.expect(pm.response.json().bloodGroup).to.eql("AB +");
        pm.expect(pm.response.json().height).to.eql(165);
        pm.expect(pm.response.json().weight).to.eql(71.1);
        pm.expect(pm.response.json().eyeColor).to.eql("black");
        pm.expect(pm.response.json().hair.color).to.eql("Black");
      });

      pm.test("Response time is less than 500ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(500);
      });
    }
  });

  postman[Request]({
    name: "PUT Request Copy",
    id: "120faae4-0814-466c-a8e1-b97b60561590",
    method: "PUT",
    address: "https://reqres.in/api/users/1",
    data:
      '{\n    "id": 1,\n    "firstName": "Akash",\n    "lastName": "Singh",\n    "age": 23,\n    "gender": "male",\n    "email": "akash.singh@knoldus.com",\n    "phone": "+91 9667305597",\n    "username": "akash1874",\n    "DateOfBirth": "1999-07-15",\n    "bloodGroup": "AB +",\n    "height": 170,\n    "weight": 71.1,\n    "eyeColor": "black",\n    "hair": {\n        "color": "Black"\n    }\n}',
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });

      pm.test("Content type is JSON", function() {
        pm.response.to.be.json;
      });

      pm.test("Response body has updated user details", function() {
        pm.expect(pm.response.text()).to.include("1");
        pm.expect(pm.response.json().firstName).to.eql("Akash");
        pm.expect(pm.response.json().lastName).to.eql("Singh");
        pm.expect(pm.response.text()).to.include("akash.singh@knoldus.com");
        pm.expect(pm.response.text()).to.include("+91 9667305597");
        pm.expect(pm.response.text()).to.include("1999-07-15");
        pm.expect(pm.response.text()).to.include("AB +");
        pm.expect(pm.response.text()).to.include("170");
        pm.expect(pm.response.text()).to.include("71.1");
        pm.expect(pm.response.text()).to.include("black");
        pm.expect(pm.response.text()).to.include("Black");
      });

      pm.test("Response time is less than 500ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(500);
      });
    }
  });

  postman[Request]({
    name: "PATCH Request Copy",
    id: "3fc839cb-678c-4ee2-b910-0a73d2d46001",
    method: "PATCH",
    address: "https://reqres.in/api/users/1",
    data:
      '{\n    "id": 1,\n    "username": "akash1800",\n    "DateOfBirth": "1999-07-15",\n    "bloodGroup": "AB +",\n    "height": 170,\n    "weight": 71.1,\n    "eyeColor": "black",\n    "hair": {\n        "color": "Black"\n    }\n}',
    post(response) {
      // Check that the response status code is 200
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });

      pm.test("Content type is JSON", function() {
        pm.response.to.be.json;
      });

      // Check that the response body includes the updated user's ID
      pm.test("Response body has updated data.", function() {
        pm.expect(pm.response.text()).to.include("1");
        pm.expect(pm.response.json().username).to.eql("akash1800");
        pm.expect(pm.response.json().DateOfBirth).to.eql("1999-07-15");
        pm.expect(pm.response.json().bloodGroup).to.eql("AB +");
        pm.expect(pm.response.json().height).to.eql(170);
        pm.expect(pm.response.json().weight).to.eql(71.1);
        pm.expect(pm.response.json().eyeColor).to.eql("black");
        pm.expect(pm.response.json().hair.color).to.eql("Black");
      });

      pm.test("Response time is less than 500ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(500);
      });
    }
  });

  postman[Request]({
    name: "DELETE Request Copy",
    id: "ddf82537-f57a-4da4-ba6d-7167b28c8445",
    method: "DELETE",
    address: "https://reqres.in/api/users/1",
    post(response) {
      pm.test("Response status code is 204", function() {
        pm.response.to.have.status(204);
      });

      pm.test("Response time is less than 500ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(500);
      });
    }
  });
}

export function handleSummary(data) {
  return {
    "Report.html": htmlReport(data),
  };
}
